---
# - name: Update RHEL-based systems
#   when: ansible_os_family == 'RedHat'
#   ansible.builtin.dnf:
#     name: '*'
#     state: latest
#     update_cache: true
#     update_only: true

- name: Register subscription for RHEL
  when: ansible_os_family == 'RedHat'
  community.general.redhat_subscription:
    username: "{{ lookup('env', 'RHN_USERNAME') }}"
    password: "{{ lookup('env', 'RHN_PASSWORD') }}"

- name: Enable repository management for RHEL
  when: ansible_os_family == 'RedHat'
  ansible.builtin.command:
    cmd: subscription-manager config --rhsm.manage_repos=1
  register: rhsm_manage_repos
  changed_when: rhsm_manage_repos.rc != 0
  
- name: Install required packages
  ansible.builtin.dnf:
    name:
      - ansible-core
      - wget
      - git-core
      - rsync
      - vim
    state: present
  become: yes

- name: Download Ansible Automation Platform setup file
  ansible.builtin.get_url:
    url: "https://github.com/Hashi-RedHat-APJ-Collab/AAP-2.5-containerized-on-AWS/raw/refs/heads/main/post_data/ansible-automation-platform-containerized-setup-2.5-13.tar.gz"
    dest: "/tmp/ansible-automation-platform-containerized-setup-2.5-13.tar.gz"
  register: download_result

- name: Get information about downloaded file
  ansible.builtin.stat: 
    path: "/tmp/ansible-automation-platform-containerized-setup-2.5-13.tar.gz"
  register: file_info

- name: Extract AAP setup archive
  ansible.builtin.unarchive:
    src: "/tmp/ansible-automation-platform-containerized-setup-2.5-13.tar.gz"
    dest: "/tmp/"
    remote_src: yes