---
# This file contains tasks to display the installation log
- name: "Check current installation status (Check {{ log_check_number }})"
  ansible.builtin.async_status:
    jid: "{{ install_job.ansible_job_id }}"
  register: current_status
  
- name: "Display log header"
  ansible.builtin.debug:
    msg: "=== Installation Log (Check {{ log_check_number }}/10) - Status: {{ 'COMPLETE' if current_status.finished else 'IN PROGRESS' }} ==="

- name: "Get log content"
  ansible.builtin.shell: "tail -n 20 /tmp/aap-install.log || echo 'Log file not yet available'"
  register: log_output
  changed_when: false
  failed_when: false
  
- name: "Display log content"
  ansible.builtin.debug:
    msg: "{{ log_output.stdout_lines }}"
    
- name: "Skip remaining checks if installation is complete"
  ansible.builtin.meta: end_play
  when: current_status.finished
