---
# playbook.yaml
- name: 'Provision Image'
  become: true
  become_method: sudo
  gather_facts: true
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
    role:
  roles:
    - "{{ role }}"

# ---
# # playbook.yml
# - name: 'Provision Image'
#   hosts: all
#   become: true

#   tasks:
#     - name: DNF update the system
#       ansible.builtin.dnf:
#         name: '*'
#         state: latest
#         update_cache: true
#         use_backend: dnf
#     - name: Install Apache
#       package:
#         name: httpd
#         state: latest
#     - name: Start Apache Service
#       ansible.builtin.service:
#         name: httpd
#         state: started
#         enabled: true
#     - name: Copy index.html
#       ansible.builtin.copy:
#         src: files/index.html
#         dest: /var/www/html/index.html
#     - name: Download and install SSM agent RPM package
#       ansible.builtin.dnf:
#         name: https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
#         state: present
#         disable_gpg_check: true